baseURL: 'https://justinmitchel.com/'
languageCode: 'en-us'
copyright: 'justinmitchel.com'
title: 'Justin Mitchel'
theme: "PaperMod"
enableEmoji: true
disqusShortname: "justinmitchel"

menu:
  main:
    - identifier: blog
      name: blog
      url: /
      weight: 10
    # - identifier: tags
    #   name: tags
    #   url: /tags/
    #   weight: 20
    - identifier: cfe
      name: work
      url: https://www.cfe.sh
      weight: 30


params:
    defaultTheme: dark
    ShowReadingTime: true
    ShowToc: true
    ShowBreadCrumbs: true
    ShowPostNavLinks: true
    ShowCodeCopyButtons: true
    comments: true


